### ISSUE TITLE
Implement Cognitive Complexity metric

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#133]
Using specification [1] implement in python CognitiveComplexity metric. 

[1].  https://www.sonarsource.com/docs/CognitiveComplexity.pdf

**Comment by acheshkov** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#133](https://github.com/yegor256/aibolit/issues/133) assigned to @tribals[/z](https://www.0crat.com/u/tribals), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/0266f6fc-b743-4f7a-88c5-024d1c9be9ff); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by tribals** [comment]
@acheshkov It is not clear what should be done to resolve the issue.

Please, provide these details:

- It is supposed to implement Cognitive Complexity metric for Java, written purely in Python? I mean, the whole algorithm of counting complexity? 
- Or it is supposed to integrate some existing tool which is capable of doing so for Java? If so, which tool? Should it be a Maven plugin, or completely independent CLI tool (like [CodeClimate](https://github.com/codeclimate/codeclimate)), or something else?
- What this metric should produce? Is there some format of result? JSON, YAML, XML, text?

**Comment by tribals** [comment]
@0crat wait

**Comment by acheshkov** [comment]
@tribals answers on your questions:

 - yes, implement using Python for Java code
 - you can use 3rd Python party libraries 
 - Metric's output is a number

**Comment by acheshkov** [comment]
@tribals any progress other questions?

**Comment by tribals** [comment]
@acheshkov Well, here is my thoughts.

> * yes, implement using Python for Java code

Unfortunately, this can't be done. At least in the single issue. The topic is complex enough at its own. I'm afraid it requires even the separate project.

> * you can use 3rd Python party libraries

There is none of such libraries - written in Python. Is is not surprising since it is not common to analyze sources in one language using tools written in another. But parsers for such a case is generally available - you can parse Python using Java and vice versa, parse Python using Ruby, parse golang using Java and so on. But that's it! Parsing only.

There is well established and mature project - [CodeClimate](https://github.com/codeclimate/codeclimate). It allows you to do a lot of analysis upon your code base, including wide range of metrics, [Cognitive Complexity](https://docs.codeclimate.com/docs/cognitive-complexity) too. It also supports many programming languages and have some kind of interface (CLI).

So, is it allowed to use such kind of tools to do this task? Seems like following this path you only need to integrate such tool and adapt result it produces to required format. But disadvantages exist too - you need to depend on Docker since each plugin (read "metric") bundled as docker image.
