### ISSUE TITLE
method_siblings pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#142]
Similar to #141. Here it is:

```java
interface Foo {
  int fileSize();
  Date fileDate();
}
```

It's not a good practice to have compound names which start with the same first word. Better rename them to `size()` and `date()`.

`file` and `fileSize` are NOT siblings.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#142](https://github.com/yegor256/aibolit/issues/142) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/8745b83c-ec59-4dd0-bb49-88dfd0280055); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for closure

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4ea0ebc5-1e90-4d29-b5a1-8c93eef19bcd, thread: pool-864-thread-1
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.13](https://github.com/zerocracy/farm): Issue: yegor256/aibolit#142, Comment: 621294998

**Comment by paulodamaso** [comment]
@acheshkov Merged, please close

**Comment by paulodamaso** [comment]
@acheshkov ping

**Comment by paulodamaso** [comment]
@0crat wait for closure

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#281](https://github.com/yegor256/aibolit/issues/281) is still not solved.

**Comment by lyriccoder** [comment]
Can we discuss this pattern? Seems it's absolutely wrong anti-pattern. If u use have compound names which start with the same first word then it is not bad.

My point is the following:

1) Method names are **ACTIONS**. We have an action and a subject. A subject is the only thing which can differ the meaning of the action (or "shorten" the context). E.g.,
you have the _calculate_ verb. If we name a function that way, we won't understand what is calculating. Calculate metrics? Calculate patterns? Calculate matches?  Calculate the average number of acnes on the faces?
But if we add a subject, the function name becomes more precise:  `calculate_patterns`.
Moreover, too often we can't just do this way:
```
calculate(metrics)
calculate(patterns)
```
It is because these functions can have different implementation. Also, both metrics and patterns can have different data structure, that's why we can;t use the same function for it. 
2) Also, the correct order in English sentence (if we talk about the verbs) is the following:

1. verb phrase + direct object

2. verb + indirect object + direct object

So, there can't be another way but to declare verb and the subject _after_ it. The first part of the compound name will be always the same.

So, if we use `calculateMetrics`, it is not bad. It's even better because functions are actions. And a subject is the only thing which can differ the meaning of the action.

**Comment by paulodamaso** [comment]
@lyriccoder I'll give my 5 cents on this:
Actually, method names doesn't always are related to actions anymore. When we start to use a more declarative approach these behaviors are composed through other objects. Take a look at:
```
public Calculation {
    Calculation (List<Metric> patterns, File file) {
        ....
    }
    public value() {
        //calculate the metrics on file
    }
}
```
In this case, the context is already shortened by the class which the method is called. Having lots of methods in the same class is a bad thing, and having a lot of method siblings may indicate that we are putting too much responsibility in a single class or we are using our methods to just expose the data (e.g. getters).

The method siblings pattern helps us to keep our design pointed to a more declarative approach, and break our classes into more concise units of code. In fact, our method action would be moved to a class whose only responsibility is this method, making our code more structured. Then we can wrap, extend, implement and reuse the object as we please or need.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#281](https://github.com/yegor256/aibolit/issues/281) is solved here.
