### ISSUE TITLE
Get rid of --filenames or --folder

### ISSUE THREAD

**Issue by g4s8** [yegor256/aibolit#363]
I'd suggest getting rid of `--filenames` or `--folder` CLI options and use argument instead, since it looks like a primary and mandatory argument for `recommend` command and can be determined easily by using `os.path`: https://stackoverflow.com/a/3204819. E.g.
 - `aibolit recommend ./src/main/java/Main.java` instead of `aibolit recommend --filenames ./src/main/java/Main.java`
 - `aibolit recommend ./src/main/java` instead of `aibolit recommend --folder ./src/main/java`

It'll be much easier to switch from folder to file when editing last command.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by lyriccoder** [comment]
at the moment we cannot do this. We have a lot for parameters for  `recommend` like --full, --model_name. That's why we have to specify `filenames` or `folder` parameter.

@acheshkov should we close it?

**Comment by yegor256** [comment]
@lyriccoder I second this. Parameters start with `--` while file names don't. This is how many other tools work, for example my XML static analyzer [xcop](https://github.com/yegor256/xcop)

**Comment by yegor256** [comment]
@yegor256 I'm closing #355 in favor of this

**Comment by yegor256** [comment]
@lyriccoder moreover, we don't need to implement recursive searching of files in folders. The user will do it using standard Linux instruments:

```
$ aibolit recommend $(find . -name '*.java')
```

**Comment by lyriccoder** [comment]
1) People complained about this `$(find . -name '*.java')`. They said that they won't search for files. They do not care how to search it. They need to just to set up a parameter. The easier usage is, the more people will use it. We shouldn't rely on `The user will do it using standard Linux instruments:`. Let's then make an input of some txt  file (instead of command line arguments) an then user will parse using standard Linux instruments awk? Will they do it? No, they need just to set a parameter
2) it's the behaviour of argparse package in python. We can't do it technically. It accepts only `--key value`. But since you want to use only list of parameters, it can be in a different place in teh command line:
`recommend --full '1.java' '2.java'`
`recommend --format=xml '1.java' '2.java' --full`
You need to find out the place where that list begins and the place where it ends. You need to write complicated code (you can't do it with `argparse` package) just because smb wants. It's not a serious problem

@acheshkov what do u think?

**Comment by acheshkov** [comment]
@lyriccoder I think the CLI shuld expect list of parameters first and the list of files or folders should be always at the tail.

```
$ aibolit recommend [--parameter=value]  [path_to_folder_or_file]   
```

**Comment by lyriccoder** [comment]
We need to find a new framework for CLI, because

1) we can have ` recommend [--parameter=value]  [path_to_folder_or_file]`, only we set a list of parameters as value for EACH parameter.  It's because we can change the order of the parameters:
--format=xml --model=1.pkl filename1 filename2
--model=1.pkl --format=xml  filename1 filename2
In this case we need to parse manually and understand that the *first* value is the real value of the current parameter:

`format=xml  filename1 filename2`, the real value for `format` is `xml`, the rest of the parameters are filenames, so we need to do it for each parameter

2) we have the `full` parameter without value, it can have not a single value, so we cannot run `aibolit ... --full filename1 filename2`. 

Should we find waste time for a new framework? Or should we the mentioned dirty hacks? We should chose the lesser of two evils

**Comment by yegor256** [comment]
@acheshkov @lyriccoder how about this:

```
$ aibolit check --exclude '**/*Test.java' --exclude /code/takes
```

It will get all files from `/code/takes` and will exclude what matches the provided [glob pattern](https://en.wikipedia.org/wiki/Glob_%28programming%29).

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#363` is not assigned, can't get performer
